import React from 'react';
import {
  Home,
  BookOpen,
  Calendar,
  Sparkles,
  MessageSquare,
  User,
  Award,
  Heart,
  Phone,
  Mail,
  FileText,
  Camera,
  Compass,
  Bookmark,
  ShieldCheck,
  Share2,
  HelpCircle,
  Star,
  Video,
  Download,
  Globe,
  Moon,
  Sun,
  Clock,
  GraduationCap,
} from 'lucide-react';

export const AVAILABLE_ICONS: { [key: string]: React.ElementType } = {
  Home,
  BookOpen,
  Calendar,
  Sparkles,
  MessageSquare,
  User,
  Award,
  Heart,
  Phone,
  Mail,
  FileText,
  Camera,
  Compass,
  Bookmark,
  ShieldCheck,
  Share2,
  HelpCircle,
  Star,
  Video,
  Download,
  Globe,
  Moon,
  Sun,
  Clock,
  GraduationCap,
};

export const AVAILABLE_ICON_NAMES = Object.keys(AVAILABLE_ICONS);

export const AVAILABLE_SECTIONS = [
  { id: 'beranda', label: 'Beranda (Hero Section)' },
  { id: 'profil', label: 'Profil & Biografi' },
  { id: 'karya', label: 'Karya & Publikasi Modul' },
  { id: 'media-channel', label: 'Siaran Media & Kanal Digital' },
  { id: 'agenda', label: 'Agenda & Jadwal Kajian' },
  { id: 'fitur-islami', label: 'Fitur Islami (Tasbih & Sholat)' },
  { id: 'galeri', label: 'Galeri & Dokumentasi Foto' },
  { id: 'kontak', label: 'Kontak & Undangan' },
];

export const FOOTER_THEMES = [
  {
    id: 'emerald_gold',
    name: 'Klasik Madrasah (Hijau Zamrud & Emas)',
    description: 'Nuansa resmi madrasah dengan latar hijau zamrud dan aksen border emas.',
    bgClass: 'bg-[#064e3b]/95 text-white border-amber-500/50',
    activeClass: 'bg-emerald-800 text-amber-300',
    accentColor: '#fbbf24',
  },
  {
    id: 'dark_emerald',
    name: 'Malam Khusyuk (Hijau Gelap Pekat)',
    description: 'Tampilan elegan gelap dengan aksen hijau zamrud bercahaya.',
    bgClass: 'bg-[#022c22]/95 text-emerald-100 border-emerald-500/40',
    activeClass: 'bg-emerald-900 text-emerald-300',
    accentColor: '#34d399',
  },
  {
    id: 'navy_gold',
    name: 'Safir Islami (Navy & Emas)',
    description: 'Nuansa biru safir berpadu tipografi emas keilmuan.',
    bgClass: 'bg-[#0f172a]/95 text-slate-100 border-amber-400/50',
    activeClass: 'bg-slate-800 text-amber-300',
    accentColor: '#f59e0b',
  },
  {
    id: 'amber_gold',
    name: 'Emas Kerajaan (Royal Amber)',
    description: 'Kemewahan nuansa emas dengan kontras teks gelap berwibawa.',
    bgClass: 'bg-gradient-to-r from-amber-700 to-amber-900 text-amber-50 border-amber-300/70',
    activeClass: 'bg-amber-800 text-white',
    accentColor: '#fde047',
  },
  {
    id: 'light_modern',
    name: 'Terang Minimalis (Light Clean)',
    description: 'Latar putih bersih dengan border zamrud halus dan bayangan modern.',
    bgClass: 'bg-white/95 text-gray-800 border-emerald-600/30 shadow-xl',
    activeClass: 'bg-emerald-100 text-emerald-900',
    accentColor: '#059669',
  },
  {
    id: 'gold_luxury',
    name: 'Kemilau Emas Klasik (Pure Gold)',
    description: 'Aksen emas terang dengan latar hijau gelap mewah.',
    bgClass: 'bg-gradient-to-r from-[#064e3b] via-[#047857] to-[#064e3b] text-amber-100 border-amber-400/60',
    activeClass: 'bg-amber-900/60 text-amber-300 border border-amber-400/40',
    accentColor: '#fbbf24',
  },
];
